#!/usr/bin/env python3
"""Regenerate the shared shell of every documentation page.

The site itself has no build step — it is a folder of static files served as-is, which is why
every asset reference is relative and nothing fetches from a network. This tool is an AUTHORING
convenience, not a deployment step: it rewrites the parts of each page that must be identical
everywhere (head, header, sidebar, on-page contents, footer) so that adding a page or renaming a
section does not mean hand-editing six files and getting five of them slightly wrong.

Run it after editing any page's headings, or after adding a page to nav.json:

    python3 _tools/build.py            # rewrite
    python3 _tools/build.py --check    # exit 1 if anything is stale (for CI)

Everything between the @shell markers is generated and will be overwritten. Everything inside
<main> is hand-written and is never touched, except that headings missing an id are given one so
they can be linked and tracked by the contents rail.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
import unicodedata
from pathlib import Path

import highlight

DOCS = Path(__file__).resolve().parent.parent
NAV = json.loads((Path(__file__).resolve().parent / "nav.json").read_text(encoding="utf-8"))

BEGIN = "<!-- @shell:{} — generated by _tools/build.py, do not edit by hand -->"
END = "<!-- @/shell:{} -->"


# --------------------------------------------------------------------------- helpers

def slug(text: str) -> str:
    """A stable, readable id from heading text."""
    text = html.unescape(re.sub(r"<[^>]+>", "", text))
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(r"[-\s]+", "-", text)[:60].strip("-")


def text_of(fragment: str) -> str:
    """Heading text with tags stripped but entities left intact for re-emission."""
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", fragment)).strip()


def split_page(src: str) -> dict:
    """Break a page into the regions this tool owns and the one it must not touch."""
    head = re.search(r"<head>(.*?)</head>", src, re.S)
    main = re.search(r"(<main\b[^>]*>)(.*?)(</main>)", src, re.S)
    if not head or not main:
        raise SystemExit("page is missing <head> or <main>")
    return {"head": head.group(1), "main_open": main.group(1), "main": main.group(2)}


# --------------------------------------------------------------------------- headings

def ensure_heading_ids(body: str) -> tuple[str, list[dict]]:
    """Give every h2/h3 a linkable id and return the resulting section tree.

    An h2 wrapped in <section id="x"> already has a target, and existing ids are load-bearing —
    the anchor lists and cross-page links point at them — so they are preserved exactly. Only
    headings with nothing to link to acquire one.
    """
    used: set[str] = set(re.findall(r'id="([^"]+)"', body))
    tree: list[dict] = []
    out: list[str] = []
    cursor = 0
    section_id: str | None = None

    pattern = re.compile(r'<section\b([^>]*)>|<(h2|h3)\b([^>]*)>(.*?)</\2>', re.S)
    for m in pattern.finditer(body):
        out.append(body[cursor:m.start()])
        cursor = m.end()

        if m.group(1) is not None:                       # a <section ...> opening tag
            found = re.search(r'id="([^"]+)"', m.group(1))
            section_id = found.group(1) if found else None
            out.append(m.group(0))
            continue

        level, attrs, inner = m.group(2), m.group(3), m.group(4)
        existing = re.search(r'id="([^"]+)"', attrs)

        if existing:
            anchor = existing.group(1)
        elif level == "h2" and section_id:
            anchor = section_id                          # the wrapper already carries the target
            section_id = None
        else:
            base = slug(inner) or f"{level}-{len(tree)}"
            anchor = base
            n = 2
            while anchor in used:
                anchor, n = f"{base}-{n}", n + 1
            used.add(anchor)
            attrs = f'{attrs} id="{anchor}"'

        tree.append({"level": level, "id": anchor, "text": text_of(inner)})
        out.append(f"<{level}{attrs}>{inner}</{level}>")

    out.append(body[cursor:])
    return "".join(out), tree


# --------------------------------------------------------------------------- content invariants

def normalise_content(body: str) -> str:
    """Fix the structural mistakes that are easy to make by hand and impossible to see in source.

    Each of these was found rendering wrongly on the live site, and each is mechanical, so the
    generator enforces it rather than trusting six pages to stay in agreement.
    """
    # A bare <table class="table"> has no scroll container. `.table` is width:100% with auto
    # layout, and the stylesheet forces white-space:nowrap on header cells and in-cell <code>, so
    # its min-content width can exceed 1200px. Nothing above it scrolls, so the overflow reaches
    # the viewport and the WHOLE PAGE scrolls sideways on a phone, dragging every paragraph with
    # it. Wrapping is the stylesheet's own intended pattern.
    def wrap_tables(text: str) -> str:
        parts = re.split(r'(<table class="table">.*?</table>)', text, flags=re.S)
        out: list[str] = []
        for part in parts:
            if part.startswith('<table class="table">') and not (
                    out and out[-1].rstrip().endswith('<div class="table-scroll">')):
                out.append(f'<div class="table-scroll">{part}</div>')
            else:
                out.append(part)
        return "".join(out)

    body = wrap_tables(body)

    # A horizontally scrollable region must be reachable by keyboard; without tabindex a keyboard
    # user simply cannot read the right-hand end of a long code line.
    body = re.sub(r'<pre class="code">', '<pre class="code" tabindex="0">', body)

    # .seq__row is a two-column grid whose FIRST item is the generated counter. Any row with more
    # than one child therefore auto-places its second, fourth… child into the 44px number column,
    # which is what renders a paragraph one word per line. Forcing every real child into column 2
    # fixes every row at once, including ones written later.
    # (Implemented in the stylesheet as `.seq__row > * { grid-column: 2 }` — see site.css.)

    # The .seq counter already draws the number in its own badge, so a literal "1. " written
    # into the step's title renders it twice. Steps are titled with <h3> on some pages and
    # <strong> on others, so strip the prefix from both — but only inside a .seq row, where the
    # counter exists. A numbered heading anywhere else is the author's own numbering.
    def drop_double_number(m):
        return re.sub(r'(<(?:h3|strong)[^>]*>)\s*\d+\.\s+', r'\1', m.group(0))
    body = re.sub(r'<div class="seq__row">.*?</div>', drop_double_number, body, flags=re.S)
    return body


# --------------------------------------------------------------------------- search

def index_entries(page: dict, body: str, tree: list[dict]) -> list[dict]:
    """One search record per section: its heading, its page, and the prose under it.

    Built here rather than in the browser, because the only other way for a static site to know
    its own contents is to fetch and parse every page on the reader's first keystroke.
    """
    plain = re.sub(r"<(script|style|pre)\b.*?</\1>", " ", body, flags=re.S)
    # Slice from the END of the tag that carries the id — starting at the attribute itself would
    # spill the rest of the opening tag into the excerpt.
    cuts = {}
    for m in re.finditer(r'id="([^"]+)"', plain):
        close = plain.find(">", m.end())
        if close != -1:
            cuts[close + 1] = m.group(1)

    out, positions = [], sorted(cuts)
    for i, start in enumerate(positions):
        end = positions[i + 1] if i + 1 < len(positions) else len(plain)
        node = next((n for n in tree if n["id"] == cuts[start]), None)
        if not node:
            continue
        text = html.unescape(re.sub(r"<[^>]+>", " ", plain[start:end]))
        text = re.sub(r"\s+", " ", text).strip()
        if len(text) < 12:
            continue
        out.append({
            "p": page["file"],
            "pt": page["nav"],
            "h": node["text"],
            "id": node["id"],
            "l": 2 if node["level"] == "h2" else 3,
            "t": text[:340],
        })
    return out


# --------------------------------------------------------------------------- regions

def asset(path: str) -> str:
    """An asset URL stamped with a short hash of its contents.

    The site sits behind a CDN with a four-hour TTL, so a redeploy that reuses a filename is
    served stale: the pages arrive new and their stylesheet arrives old, which renders the
    layout as an unstyled list until the cache expires. A URL that changes when the bytes change
    cannot be served stale, and needs no cache purge on deploy.
    """
    f = DOCS / path
    if not f.exists():
        return path
    return f"{path}?v={hashlib.sha256(f.read_bytes()).hexdigest()[:10]}"


def render_head(page: dict, site: dict) -> str:
    """The <head>. Identical everywhere except title, description and canonical URL."""
    title = html.escape(page["title"])
    desc = html.escape(page["description"])
    canonical = site["url"].rstrip("/") + "/" + page["file"]
    # Absolute, because a scraper resolves it out of context — but still versioned:
    # Slack, Teams and X cache a card image far longer than the page that names it.
    social = site["url"].rstrip("/") + "/" + asset(site["card"])
    return f"""<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{canonical}">

<meta property="og:type" content="website">
<meta property="og:site_name" content="{html.escape(site['name'])}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{canonical}">
<meta property="og:image" content="{social}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="{social}">

<meta name="theme-color" content="#121e4c">
<link rel="icon" href="{asset("assets/img/favicon.svg")}" type="image/svg+xml">
<link rel="apple-touch-icon" href="{asset("assets/img/apple-touch-icon.png")}">
<link rel="stylesheet" href="{asset("assets/css/site.css")}">"""


def render_header(page: dict, site: dict) -> str:
    return f"""<a class="skip-link" href="#main">Skip to content</a>

<header class="site-header">
  <div class="site-header__inner">
    <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="sidebar"
            aria-label="Open navigation">
      <span class="nav-toggle__bars" aria-hidden="true"></span>
    </button>

    <a class="site-header__brand" href="./index.html">
      <img src="assets/img/amthal-logo-white.svg" alt="Amthal Group" width="112" height="34">
      <span class="site-header__title">{html.escape(site['name'])}</span>
    </a>

    <button class="search-trigger" type="button" data-search-open
            aria-label="Search the documentation">
      <svg viewBox="0 0 20 20" aria-hidden="true" focusable="false">
        <circle cx="9" cy="9" r="6"></circle><path d="M13.5 13.5 17.5 17.5"></path>
      </svg>
      <span>Search</span>
      <kbd>/</kbd>
    </button>

    <a class="site-header__repo" href="{site['repo']}" rel="noopener">
      <svg viewBox="0 0 16 16" aria-hidden="true" focusable="false" width="18" height="18">
        <path d="M8 0C3.58 0 0 3.58 0 8a8 8 0 0 0 5.47 7.59c.4.07.55-.17.55-.38
                 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01
                 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95
                 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82a7.42 7.42 0 0 1 4 0c1.53-1.04
                 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65
                 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16
                 8c0-4.42-3.58-8-8-8Z"></path>
      </svg>
      <span class="visually-hidden">Source on GitHub</span>
    </a>
  </div>
</header>"""


def render_sidebar(current: dict, tree: list[dict], site: dict) -> str:
    """Every page, grouped, with the current page's sections expanded beneath it."""
    groups: list[tuple[str, list[dict]]] = []
    for p in NAV["pages"]:
        if not p.get("listed", True):
            continue
        if not groups or groups[-1][0] != p["group"]:
            groups.append((p["group"], []))
        groups[-1][1].append(p)

    out = ['<aside class="sidebar" id="sidebar" data-sidebar>',
           '  <nav class="sidebar__nav" aria-label="Documentation">']
    for name, pages in groups:
        out.append(f'    <p class="sidebar__group">{html.escape(name)}</p>')
        out.append('    <ul class="sidebar__list">')
        for p in pages:
            here = p["file"] == current["file"]
            cur = ' aria-current="page"' if here else ""
            out.append(f'      <li><a href="./{p["file"]}"{cur}>{html.escape(p["nav"])}</a>')
            if here:
                sections = [n for n in tree if n["level"] == "h2"]
                if sections:
                    out.append('        <ul class="sidebar__sections">')
                    for s in sections:
                        out.append(
                            f'          <li><a href="#{s["id"]}">{html.escape(s["text"])}</a></li>')
                    out.append('        </ul>')
            out.append('      </li>')
        out.append('    </ul>')
    out.append('  </nav>')
    out.append(f'''  <p class="sidebar__meta">
    SDK {site["sdkVersion"]} · Bridge protocol v{site["protocol"]}<br>
    <a href="{site["repo"]}" rel="noopener">GitHub</a> ·
    <a href="{site["repo"]}/issues" rel="noopener">Issues</a>
  </p>''')
    out.append('</aside>')
    return "\n".join(out)


def render_toc(tree: list[dict]) -> str:
    """The contents rail. Empty pages get an empty rail rather than a broken one."""
    items = [n for n in tree if n["level"] in ("h2", "h3")]
    if len(items) < 3:
        return '<div class="toc" aria-hidden="true"></div>'
    out = ['<nav class="toc" aria-labelledby="toc-title" data-toc>',
           '  <p class="toc__title" id="toc-title">On this page</p>',
           '  <ul>']
    for n in items:
        cls = ' class="toc__sub"' if n["level"] == "h3" else ""
        out.append(f'    <li{cls}><a href="#{n["id"]}">{html.escape(n["text"])}</a></li>')
    out.append('  </ul>')
    out.append('</nav>')
    return "\n".join(out)


def render_footer(site: dict) -> str:
    return f"""<footer class="site-footer">
  <div class="site-footer__inner">
    <div class="site-footer__brand">
      <img src="assets/img/amthal-logo-white.svg" alt="Amthal Group" width="112" height="34">
      <p>Amthal Portal SDK {site['sdkVersion']} — Bridge Protocol v{site['protocol']}.<br>
         Embed the Client Portal, and every form your tenant publishes in it, in a native app.</p>
    </div>
    <div class="site-footer__cols">
      <div>
        <p class="site-footer__head">Documentation</p>
        <ul>
          <li><a href="./getting-started.html">Getting started</a></li>
          <li><a href="./configuration.html">Configuration</a></li>
          <li><a href="./api-reference.html">API reference</a></li>
          <li><a href="./recipes.html">Recipes</a></li>
        </ul>
      </div>
      <div>
        <p class="site-footer__head">Reference</p>
        <ul>
          <li><a href="./bridge-protocol.html">Bridge protocol</a></li>
          <li><a href="./security.html">Security</a></li>
          <li><a href="./troubleshooting.html">Troubleshooting</a></li>
        </ul>
      </div>
      <div>
        <p class="site-footer__head">Project</p>
        <ul>
          <li><a href="{site['repo']}" rel="noopener">Source on GitHub</a></li>
          <li><a href="{site['repo']}/issues" rel="noopener">Report an issue</a></li>
          <li><a href="{site['repo']}/blob/main/LICENSE" rel="noopener">MIT licence</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<script src="{asset("assets/js/site.js")}"
        data-search-index="{asset("assets/search-index.json")}" defer></script>"""


# --------------------------------------------------------------------------- assembly

def marked(name: str, content: str) -> str:
    return f"{BEGIN.format(name)}\n{content}\n{END.format(name)}"


def build_page(page: dict, site: dict) -> str:
    src = (DOCS / page["file"]).read_text(encoding="utf-8")
    parts = split_page(src)

    # The in-content "On this page" blocks are superseded by the contents rail; two lists of the
    # same links, one of them not tracking the reader's position, is worse than one. Strip them
    # BEFORE reading the heading tree — one of them wraps a heading of its own, so removing them
    # afterwards would change the tree the rail was built from and take a second pass to settle.
    body = re.sub(r'\s*<nav class="anchor-list" aria-label="On this page">.*?</nav>\n?',
                  "\n", parts["main"], flags=re.S)
    body = re.sub(r'\s*<nav aria-label="On this page">.*?</nav>\n?', "\n", body, flags=re.S)

    body = normalise_content(body)
    body, painted = highlight.apply(body)
    body, tree = ensure_heading_ids(body)
    records = index_entries(page, body, tree)
    page["_painted"] = painted

    return records, f"""<!DOCTYPE html>
<html lang="en">
<head>
{marked('head', render_head(page, site))}
</head>
<body>

{marked('header', render_header(page, site))}

<div class="layout">
{marked('sidebar', render_sidebar(page, tree, site))}

<main class="content" id="main">
{body.strip()}
</main>

{marked('toc', render_toc(tree))}
</div>

{marked('footer', render_footer(site))}

</body>
</html>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report stale pages and exit non-zero instead of rewriting")
    args = ap.parse_args()

    site, stale = NAV["site"], []
    present = [p for p in NAV["pages"] if (DOCS / p["file"]).exists()]
    for page in NAV["pages"]:
        if page not in present:
            print(f"  skip   {page['file']} (not written yet)")

    # Two passes, because the pages carry a content hash of the search index and the index is
    # built from the pages. Pass one exists only to settle the index; pass two renders against
    # the final hash, so a single run is already idempotent.
    index: list[dict] = []
    for page in present:
        records, _ = build_page(page, site)
        index.extend(records)

    index_path = DOCS / "assets" / "search-index.json"
    payload = json.dumps(index, ensure_ascii=False, separators=(",", ":")) + "\n"
    index_current = index_path.exists() and index_path.read_text(encoding="utf-8") == payload
    if index_current:
        print(f"  ok     assets/search-index.json ({len(index)} sections)")
    elif args.check:
        print("  STALE  assets/search-index.json")
        stale.append("assets/search-index.json")
    else:
        index_path.write_text(payload, encoding="utf-8")
        print(f"  wrote  assets/search-index.json ({len(index)} sections)")

    for page in present:
        path = DOCS / page["file"]
        _, new_html = build_page(page, site)
        if path.read_text(encoding="utf-8") == new_html:
            print(f"  ok     {page['file']}")
            continue
        stale.append(page["file"])
        if args.check:
            print(f"  STALE  {page['file']}")
        else:
            path.write_text(new_html, encoding="utf-8")
            print(f"  wrote  {page['file']} ({page.get('_painted', 0)} code blocks highlighted)")

    listed = [p for p in NAV["pages"] if p.get("listed", True)
              and (DOCS / p["file"]).exists()]
    base = site["url"].rstrip("/")
    urls = "\n".join(
        f"  <url><loc>{base}/{p['file']}</loc></url>" for p in listed)
    extra = {
        "sitemap.xml": f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{urls}
</urlset>
''',
        "robots.txt": f"User-agent: *\nAllow: /\n\nSitemap: {base}/sitemap.xml\n",
    }
    for name, body in extra.items():
        path = DOCS / name
        if path.exists() and path.read_text(encoding="utf-8") == body:
            print(f"  ok     {name}")
        elif args.check:
            print(f"  STALE  {name}")
            stale.append(name)
        else:
            path.write_text(body, encoding="utf-8")
            print(f"  wrote  {name}")

    if args.check and stale:
        print(f"\n{len(stale)} page(s) stale — run: python3 _tools/build.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
